### ISSUE TITLE
⚡ Reimplement connector management

### ISSUE THREAD

**Issue by tjarbo** [tjarbo/discord-moodle-bot#130]
> **As a** User
> **I want** create, delete and edit new connectors right from the web-interface
> **so that** I can manage e.g multiple discord channels

## Description:
With #119 it's not possible anymore to edit the connectors. With this ~user story~ epic it is time to redesign the API to allow CRUD operations on connectors now. The draft is: 

- [x] `GET /api/connectors` to get a list of all connectors #144 
- [x] `POST /api/connectors` to register a new connector #151 
- ~[ ] `GET /api/connectors/:id ` to get information about connector~ Not needed right know
- [x] `PATCH /api/connectors/:id` to update a connector #145
- [x] `DELETE /api/connectors/:id ` to delete a give connector #146
- [ ] #171

### Checklist:
* [x] Re-implement API with the given endpoints
* [x] Delete old unused endpoints
* [x] Update documentation 
* [x] Rename bots to connectors @ frontend

**Comment by tjarbo** [comment]
This user story is to much for one story -> new tickets will be created

**Comment by tjarbo** [comment]
This issue will be closed, because #171 is its own user story and with #200 finally the documentation is on the newest version.
